export const ENV_KEYS = {
  API_KEY: 'API_KEY',
  WEBHOOK_SECRET: 'WEBHOOK_SECRET',
  ALGO: 'ALGO',
  DIGEST: 'DIGEST',
  DB_TYPE: 'DB_TYPE',
  DB_HOST: 'DB_HOST',
  DB_PORT: 'DB_PORT',
  DB_USER_NAME: 'DB_USER_NAME',
  DB_PASSWORD: 'DB_PASSWORD',
  DB_NAME: 'DB_NAME',
  PREFIX: 'PREFIX',
} as const;
